import type { Metadata } from "next";
/* 
import localFont from "next/font/local"; */
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";

config.autoAddCss = false;

/* const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

*/
export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-secondary-shades">
        <Provider>
          <main>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
