import Footer from "@/components/Footer";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";

/* export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by create next app",
};  */

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-secondary-shades">
        <div className="flex flex-row">
          <div className="navBar">
            <NavBar />
          </div>
          <div className="principal-grid">
            <Header />
            <main className="main-grid">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
